// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzChyIlxR9b3XP2khbVKqmMeGlx4v2GBg',
    appId: '1:187221253897:web:2a4384e3d03ce32489fdd8',
    messagingSenderId: '187221253897',
    projectId: 'gestaoos-40216',
    authDomain: 'gestaoos-40216.firebaseapp.com',
    storageBucket: 'gestaoos-40216.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-YRhdXuHqqOeI-h7m0tJS0U0ZUt2_IVw',
    appId: '1:187221253897:android:de200b49e167ca7a89fdd8',
    messagingSenderId: '187221253897',
    projectId: 'gestaoos-40216',
    storageBucket: 'gestaoos-40216.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvaAbDLSlU5d_upgxCvaIzWMn353zYoLs',
    appId: '1:187221253897:ios:08635af8d1e6cdd689fdd8',
    messagingSenderId: '187221253897',
    projectId: 'gestaoos-40216',
    storageBucket: 'gestaoos-40216.firebasestorage.app',
    iosBundleId: 'com.example.gestaoLoja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvaAbDLSlU5d_upgxCvaIzWMn353zYoLs',
    appId: '1:187221253897:ios:08635af8d1e6cdd689fdd8',
    messagingSenderId: '187221253897',
    projectId: 'gestaoos-40216',
    storageBucket: 'gestaoos-40216.firebasestorage.app',
    iosBundleId: 'com.example.gestaoLoja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzChyIlxR9b3XP2khbVKqmMeGlx4v2GBg',
    appId: '1:187221253897:web:28d63a1ea3c9f8ea89fdd8',
    messagingSenderId: '187221253897',
    projectId: 'gestaoos-40216',
    authDomain: 'gestaoos-40216.firebaseapp.com',
    storageBucket: 'gestaoos-40216.firebasestorage.app',
  );
}
